import { CodeBuilder } from "../codegen/builder";

export function generateCommonHelper(): string {
    const b = new CodeBuilder();
    b.line("import { Result, err, ok } from 'neverthrow';");
    b.line("import { z } from 'zod';");
    b.line("import { httpAdapter } from './http-adapter';");
    b.line("import { ValidationError, HttpError, formatError, AppError } from './errors';");
    b.blank();

    b.line("export async function request<T, P>(options: {");
    b.indent();
    b.line("path: string;");
    b.line("method: string;");
    b.line("params?: P;");
    b.line("paramsSchema?: z.ZodType<P>;");
    b.line("bodySchema?: z.ZodType<any>;");
    b.line("explicitQueryKeys?: string[];");
    b.line("body?: any;");
    b.line("headers?: Record<string, string>;");
    b.line("cookies?: Record<string, string>;");
    b.line("contentType?: string;");
    b.dedent();
    b.line("}): Promise<Result<T, AppError>> {");
    b.indent();
    b.line("const {");
    b.indent();
    b.line("path,");
    b.line("method,");
    b.line("params,");
    b.line("paramsSchema,");
    b.line("bodySchema,");
    b.line("explicitQueryKeys = [],");
    b.line("body,");
    b.line("headers = {},");
    b.line("cookies = {},");
    b.line("contentType = 'application/json'");
    b.dedent();
    b.line("} = options;");
    b.blank();
    b.line("const queryParamsObj = new URLSearchParams();");
    b.line("const paramsRecord = (params || {}) as Record<string, unknown>;");
    b.blank();
    b.line("if (paramsSchema && params) {");
    b.indent();
    b.line("try {");
    b.indent();
    b.line("paramsSchema.parse(params);");
    b.dedent();
    b.line("} catch (error: unknown) {");
    b.indent();
    b.line("return err(new ValidationError(formatError(error)) as any);");
    b.dedent();
    b.line("}");
    b.dedent();
    b.line("}");
    b.blank();
    b.line("const explicitKeysSet = new Set(explicitQueryKeys);");
    b.line("explicitQueryKeys.forEach((key) => {");
    b.indent();
    b.line("if (paramsRecord[key] !== undefined) {");
    b.indent();
    b.line("queryParamsObj.append(key, String(paramsRecord[key]));");
    b.dedent();
    b.line("}");
    b.dedent();
    b.line("});");
    b.blank();
    b.line("Object.entries(paramsRecord).forEach(([key, value]) => {");
    b.indent();
    b.line("if (value !== undefined && !explicitKeysSet.has(key)) {");
    b.indent();
    b.line("queryParamsObj.append(key, String(value));");
    b.dedent();
    b.line("}");
    b.dedent();
    b.line("});");
    b.blank();
    b.line("const queryString = queryParamsObj.toString();");
    b.line("const url = path + (queryString ? '?' + queryString : '');");
    b.blank();
    b.line("if (bodySchema && body) {");
    b.indent();
    b.line("try {");
    b.indent();
    b.line("bodySchema.parse(body);");
    b.dedent();
    b.line("} catch (error: unknown) {");
    b.indent();
    b.line("return err(new ValidationError(formatError(error)) as any);");
    b.dedent();
    b.line("}");
    b.dedent();
    b.line("}");
    b.blank();
    b.line("let serializedBody = body;");
    b.line("if (body) {");
    b.indent();
    b.line("if (contentType === 'application/json') {");
    b.indent();
    b.line("serializedBody = JSON.stringify(body);");
    b.dedent();
    b.line("} else if (contentType === 'application/x-www-form-urlencoded') {");
    b.indent();
    b.line("serializedBody = new URLSearchParams(body as Record<string, string>).toString();");
    b.dedent();
    b.line("}");
    b.dedent();
    b.line("}");
    b.blank();
    b.line("const mergedHeaders: Record<string, string> = {");
    b.indent();
    b.line("'Content-Type': contentType,");
    b.line("...headers");
    b.dedent();
    b.line("};");
    b.blank();
    b.line("if (cookies && Object.keys(cookies).length > 0) {");
    b.indent();
    b.line("mergedHeaders['Cookie'] = Object.entries(cookies)");
    b.indent();
    b.line(".map(([k, v]) => k + '=' + v)");
    b.line(".join('; ');");
    b.dedent();
    b.dedent();
    b.line("}");
    b.blank();
    b.line("return await httpAdapter.request<T>(url, {");
    b.indent();
    b.line("method,");
    b.line("headers: mergedHeaders,");
    b.line("body: serializedBody");
    b.dedent();
    b.line("});");
    b.dedent();
    b.line("}");

    return b.toString();
}
